### PR TITLE
doc: charge SRD

### PR DESCRIPTION
**Pull request by jpellois**
Copy original file

### CODE REVIEW

**Comment by RPDeshaies** [comment]
Hmm hi!

What is this PR for ? I see the Charge RPG file with a FR suffix though nothing has changed in the file yet AFAIK?

Are you planning on translating Charge ?

**Comment by jpellois** [comment]
Hi !
Yes, I am planning to translate Charge in french.
But I have done a bad operation on pull request...
I tried to removed myrequest but i'm loosing mysef on Git...
Sorry to disturb you !
You can (of course) refuse it !
I will try to post my french version when it will be finished

**Comment by RPDeshaies** [comment]
Are you looking at translating the entire Charge RPG document (it's can prove to be a big task since its a big document) or the SRD (which is like 80% smaller in scale)

**Comment by jpellois** [comment]
all the document

**Comment by RPDeshaies** [comment]
Oh woa this is amazing. Do you want me to create the documents and drop them in the main branch for you to merge your files in them once ready ?

**Comment by jpellois** [comment]
OK.
I think it will be better to do like that !

**Comment by RPDeshaies** [comment]
Both docs have been added to the folder here!

https://github.com/fariapp/fari-games/tree/main/public/documents/fari-games

**Comment by RPDeshaies** [comment]
Hey @jpellois,  have you started the work on this? Otherwise they are also people in the discord interested in doing this. 

Would you mind joining the discord so that we can organize all of this?
https://fari.community/discord

**Comment by jpellois** [comment]
Hello, 
Well...I have just translated the little begining (see [charge-rpg-fr.md](https://github.com/fariapp/fari-games/files/7872895/charge-rpg-fr.md))
I am ok of course if someone else can take the leadership for this tranlation because I had difficulties to take time since the begining (due to personal reason)
I am also not so much connected on discord and I think this project will be more dynamic if you can follow  this person directly on discord.
So, if you are ok, I let you give this work to this person.
Best regards

**Comment by RPDeshaies** [comment]
Well you could also collaborate with us if you're interested ? :) I'd love for you to be involved in the project if you want too.

**Comment by jpellois** [comment]
OK to collaborate with you.
It would be great to coordinate so that we can define the tasks/millestones, etc depending on our time/activites ! :-)

**Comment by RPDeshaies** [comment]
Sure! I can create a specific channel for this in Discord! 

Just follow this link and we will set everything up ^^
https://fari.community/discord

**Pull request closed without merging**
