### PR TITLE
Added French version of Dash (Fari Games)

### LINKED ISSUE #61: French translation for Dash
Hello there,

As far as I know, there's no French translation for Dash. And as I saw in #42, it's as open as "please make a PR". So, unless someone tells me that there's already one in progress, I'll start a French version... now!

### PR DESCRIPTION
**Pull request by brunobord**
closes #61

For this French translation, I've tried to use as much as possible the current French translation of Charge SRD, which is available in the same repository. Some paragraphs and terms are directly copied from it, and I'd like to thank the translators for their remarkable work.

Although, I've adopted a major change I want to explicit here. The English term _momentum_ was translated as _initiative_ in the Charge translation. Personally, I felt it didn't fit the idea of a pushing-forward force, something that was increasing the pace of the action as the story progresses. "Initiative" felt like something happening at the _beginning_ of the story, and not throughout it.

So I've picked the French word _impulsion_, because I think it reflects the idea I've expressed just above: something accelerating the rhythm, building up the… momentum.

### CODE REVIEW

**Comment by RPDeshaies** [comment]
Oh the switch from initiative to impulsion is interesting. I'll run it with the original translators on discord, but I remember we had a very thorough discussion on this subject. It's possible we might keep initiative, but we will see!

Big thanks for this! 

Long story short, my laptop broke, and its being repaired. I have a temporary laptop but I havent installed publisher on it since its temporary. As soon as I get my old laptop back, I'll try to work on a PDF version of this!

**Comment by RPDeshaies** [comment]
(you can ignore the failed build, its normal that it can't deploy from a fork!)

**Comment by brunobord** [comment]
Well, I don't know what are the next steps.
I've "just" added the Markdown file, but I have no idea on how to integrate it to the fari-games website… Would just a merge of this PR enough?

**Comment by RPDeshaies** [comment]
It would! I was planning on merging it on Monday! 😊

**Pull request merged**
